import os
from dotenv import load_dotenv

load_dotenv()


BACKEND_URL = os.getenv('CKEDITOR_BACKEND_URL')
AUDIT_DATABASE_URL = os.getenv('AUDIT_DATABASE_URL')
CKEDITOR_DATABASE_URL = os.getenv('CKEDITOR_DATABASE_URL')
CKEDITOR_COLLAB_ACCESS_KEY = os.getenv("CKEDITOR_COLLAB_ACCESS_KEY")
CKEDITOR_COLLAB_ENV_ID = os.getenv("CKEDITOR_COLLAB_ENV_ID")
CKEDITOR_COLLAB_API_SECRET = os.getenv("CKEDITOR_COLLAB_API_SECRET")
CKEDITOR_COLLAB_API_URL = os.getenv("CKEDITOR_COLLAB_API_URL")
CKEDITOR_COLLAB_ORG_ID = os.getenv("CKEDITOR_COLLAB_ORG_ID")